variables:
  # Change cache directories to be inside the project directory since we
  # can only cache paths that are in the local working copy.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  PYRIGHT_PYTHON_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pyright"
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"

stages:
  - check-format
  - build
  - test
  - publish

default:
  tags: ['shared']
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.10
  # Cache package downloads when possible.
  cache:
    key: python-packages
    paths:
      - .cache
  before_script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip3 install --index-url "$INTERNAL_PIP_INDEX" -r requirements-dev.txt

check-format:
  stage: check-format
  script:
    - |
      pre-commit run --all-files --show-diff-on-failure || ( (cat <<EOF
      =========================================================================
      If this stage fails, the formatting of your changes may be incorrect.
      To automatically format your files, install pre-commit:
          pip3 install pre-commit
          pre-commit install
      pre-commit will now automatically format any files before committing.
      To fix any misformatted files, run:
          pre-commit run --all-files
      And then commit any changes.
      More information regarding pre-commit can be found at
      https://pre-commit.com
      =========================================================================
      EOF
      ) && exit 1)

test_prerelease:
  stage: test
  needs: [check-format]
  # Use manylinux image so we can test multiple python versions.
  image: quay.io/pypa/manylinux_2_28_x86_64
  before_script:
    # Use `uv` because manylinux does not put `pip` in the default path.
    - uv venv --python=3.10
    - uv pip install --index-url=$INTERNAL_PIP_INDEX -r requirements-dev.txt
  allow_failure: true
  script:
    - .venv/bin/tox run-parallel -m prerelease
  artifacts:
    when: always
    # Store the coverage data in an artifact. It will be uploaded to gitlab by
    # the test_module job.
    paths:
      - junit-*.xml
      - .coverage.*

test_module:
  stage: test
  needs: [check-format, test_prerelease]
  # Use manylinux image so we can test multiple python versions.
  image: quay.io/pypa/manylinux_2_28_x86_64
  before_script:
    # Use `uv` because manylinux does not put `pip` in the default path.
    - uv venv --python=3.10
    - uv pip install --index-url=$INTERNAL_PIP_INDEX -r requirements-dev.txt
  script:
    - .venv/bin/tox run-parallel
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: junit-*.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

.publish-development:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"'
    - if: '$CI_COMMIT_TAG =~ /^v\d[.\d]+/'

publish_internal:
  stage: publish
  extends: .publish-development
  variables:
    TWINE_REPOSITORY_URL: https://$INTERNAL_PYPI_URL
    TWINE_USERNAME: __token__
    # This job uses GL_PKG_API_TOKEN instead of CI_JOB_TOKEN because the
    # latter does not have write access to the common package repository.
    TWINE_PASSWORD: $GL_PKG_API_TOKEN
  script:
    - pip install --index-url "$INTERNAL_PIP_INDEX" -r requirements-dev.txt
    - pip wheel --no-deps --wheel-dir=dist .
    - twine upload --verbose dist/*.whl

publish_external:
  stage: publish
  variables:
    TWINE_USER_NAME: __token__
    TWINE_PASSWORD: $PYPI_API_KEY
  script:
    - pip install --index-url "$INTERNAL_PIP_INDEX" -r requirements-dev.txt
    - pip wheel --no-deps --wheel-dir=dist .
    - VERSION=$(python3 -c "import pkginfo, sys; print(pkginfo.Wheel(sys.argv[1]).version)" dist/*.whl
    # Do not publish .dev versions on the public pypi
    - if [[ "$VERSION" =~ \.dev ]]; then exit 1; fi
    - twine upload --verbose dist/*.whl
  rules:
    # Only publish to the public pypi if PYPI_API_KEY is defined for this
    # project and this is a release.
    - if: '$PYPI_API_KEY && $CI_COMMIT_TAG =~ /^v\d[.\d]+/'
