stages:
    - check-format
    - test
    - build
    - deploy

default:
  image: python:3-slim
  tags: ["kubernetes"]

check-format:
  stage: check-format
  script:
    - apt update -y && apt install -y git
    - pip3 install pre-commit
    - |+
      pre-commit run --all-files --show-diff-on-failure || ( (cat <<EOF
      ================================================================================
      If this stage fails, the formatting of your changes may be incorrect.
      To automatically format your files, install pre-commit:
          pip3 install pre-commit
          pre-commit install
      pre-commit will now automatically format any files before commit.
      To fix any misformatted files, run:
          pre-commit run --all-files
      And then commit any changes.
      More information regarding pre-commit can be found at https://pre-commit.com.
      ================================================================================
      EOF
      ) && exit 1)

test:
  stage: test
  image: $CI_REGISTRY/rewriting/ddisasm/ubuntu20
  script:
    - mkdir pkgs
    - pushd pkgs
    - curl -L https://git.grammatech.com/rewriting/extra-packages/-/jobs/artifacts/master/download?job=capstone-linux-deb --output "capstone-artifacts.zip"
    - unzip capstone-artifacts.zip
    - curl -L https://git.grammatech.com/rewriting/gtirb/-/jobs/artifacts/master/download?job=debian-installer-ubuntu20 --output "gtirb-ubuntu20-artifacts.zip"
    - unzip gtirb-ubuntu20-artifacts.zip
    - curl -L https://git.grammatech.com/rewriting/gtirb-pprinter/-/jobs/artifacts/master/download?job=debian-installer-ubuntu20 --output "gtirb-pprinter-ubuntu20-artifacts.zip"
    - unzip gtirb-pprinter-ubuntu20-artifacts.zip
    - dpkg-scanpackages . /dev/null > Packages
    - echo -e "\ndeb [trusted=yes] file:$PWD ./\n" >> /etc/apt/sources.list
    - apt-get update -y
    - apt-get install -y --allow-unauthenticated gtirb-pprinter
    - popd
    - pip3 install  '.[test]'
    - pip3 install -e .
    - pytest --cov=gtirb_rewriting --cov-fail-under=50

build:
  stage: build
  script:
    - pip3 install twine wheel setuptools --upgrade
    - python3 setup.py sdist bdist_wheel
  artifacts:
    paths: [dist]
    expire_in: 1 week

internal-pypi:
  stage: deploy
  only: [main]
  script:
    - pip3 install twine wheel setuptools --upgrade
    - rm -rf build dist *.egg-info
    - python3 setup.py sdist bdist_wheel
    - twine check dist/*
    - echo 0 > exitcode.txt
    - (twine upload --verbose --repository-url $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/pypi --username gitlab-ci-token --password "$CI_JOB_TOKEN" dist/* | tee response.txt) || (echo $? > exitcode.txt; exit 0)
    # do not fail if we try to re-upload a package of the same version
    - if [[ "$(cat exitcode.txt)" != 0 && -z "$(cat response.txt | grep "File name has already been taken")" ]];
      then
        exit 1;
      fi

external-pypi:
  stage: deploy
  only: [main]
  script:
    - apt update -y && apt install -y curl
    - pip3 install .
    - VERSION=$(python3 -c "import gtirb_rewriting; print(gtirb_rewriting.__version__)")
    - RESPONSE_CODE=$(curl -Ls -o /dev/null -w "%{http_code}" https://pypi.org/project/gtirb-rewriting/${VERSION}/)
    - if [ "$RESPONSE_CODE" = "404" ];
      then
        pip3 install twine wheel setuptools --upgrade;
        python3 setup.py sdist bdist_wheel;
        twine check dist/*;
        twine upload dist/* -u __token__ -p $PYPI_API_KEY;
      fi
