repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: flake8
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: ["--line-length", "79"]
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.19
    hooks:
      - id: isort
        files: \.py$
  - repo: https://gitlab.com/devopshq/gitlab-ci-linter
    rev: v1.0.0
    hooks:
      - id: gitlab-ci-linter
        files: \.ci/gitlab\-ci\.yaml
        args:
          - --server=https://git.grammatech.com
          - --filename=.gitlab-ci.yaml
