FROM ubuntu:20.04

ARG NODE_VERSION=20.16.0

RUN apt-get update -y && \
    apt-get install -y \
        curl \
        gcc \
        git \
        python3 \
        python3-pip \
        python3-setuptools \
        python3-venv

RUN curl -o- https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz | \
    tar --strip-components 1 -Jxvf - --directory /usr/local/
