[tox]
requires =
    tox >= 4.0
    # Use `uv` to enable installing oldest compatible versions.
    tox-uv ~= 1.26

env_list =
    # Check types with pyright
    pyright-{oldest,newest}
    # Check all supported python versions against the oldest as well as newest
    # versions of dependencies.
    py3{8-13}-{oldest,newest}
    # Combine coverage reports from all environments into a final report.
    report

# Convenience labels for running oldest/newest/prerelease tests with all
# supported versions of python.
labels =
    oldest = pyright-oldest, py3{8-13}-oldest
    newest = pyright-newest, py3{8-13}-newest
    prerelease = pyright-prerelease, py3{8-13}-prerelease

########
# Shared settings for all environments.

[testenv]
# Build the package into a wheel before installing. This checks the build
# process for compatibility with the python version being tested.
package = wheel
setenv =
    # Get the index-url from the environment. Falls back to pypi.org if unset.
    UV_DEFAULT_INDEX = {env:UV_DEFAULT_INDEX:{env:PIP_INDEX_URL:}}
    # Write coverage to separate files to enable parallel testing.
    COVERAGE_FILE = .coverage.{envname}

uv_resolution =
    !oldest: highest       # install the newest available versions
    oldest: lowest-direct  # install the oldest available versions
pip_pre =
    prerelease: true       # install pre-release versions
    !prerelease: false     # do not install pre-release versions

########
# Type checking.

[testenv:pyright-{oldest,newest,prerelease}]
description = check types with pyright
passenv = PYRIGHT_PYTHON_CACHE_DIR
deps = -r requirements-tests.txt
commands = pyright
base_python =
    oldest: 3.8

########
# Test matrix.

[testenv:py3{8-13}-{oldest,newest,prerelease}]
description = run the tests with pytest under {envname}
deps = -r requirements-tests.txt
commands =
    # Create separate test result reports for each environment.
    pytest {posargs:--cov --junit-xml=junit-{envname}.xml --junit-prefix={envname}}

########
# Combine coverage reports.

[testenv:report]
description = report coverage from recent tests
# Make sure all tests have been run before combining coverage.
depends = py3{8-13}-{oldest,newest,prerelease}
# No need to install the package.
skip_install = true
parallel_show_output = true
deps = -r requirements-tests.txt
setenv =
    COVERAGE_FILE = .coverage
commands =
    coverage combine
    # The XML report is not written if coverage is below the threshold set in
    # pyproject.toml. Setting it to 0 here ensures the report is always
    # written. The `coverage report` command below will always print the text
    # report to the log, even if it then fails because of low coverage.
    coverage xml --fail-under=0
    coverage report --omit='tests/*'
